data = {"tech": ["Researchers have developed a new algorithm for faster image recognition.",
                 "The latest smartphone model boasts an improved camera with advanced AI capabilities.",
                 "SpaceX successfully launched another batch of Starlink satellites into orbit.",
                 "Quantum computing breakthrough: Scientists achieve longest coherence time yet.",
                 "Apple unveils its newest lineup of MacBook Pro laptops with M1 Pro and M1 Max chips."
                 "Google announces breakthrough in natural language processing with BERT model.",
                 "Electric car sales surge as companies invest in sustainable transportation.",
                 "Facebook unveils plans for virtual reality metaverse platform.",
                 "AI-powered chatbots revolutionize customer service industry.",
                 "Amazon Web Services introduces new tools for cloud computing and machine learning.",
                 "Tesla announces plans to build a new Gigafactory for battery production in Europe.",
                 "Microsoft announces breakthrough in quantum computing research.",
                 "Cybersecurity concerns rise as ransomware attacks target critical infrastructure.",
                 "The Internet of Things (IoT) revolutionizes industries with interconnected smart devices.",
                 "NVIDIA unveils new graphics card lineup for gamers and content creators.",
                 "Google's DeepMind achieves milestone in protein folding prediction with AlphaFold.",
                 "Apple announces plans to release a foldable iPhone in the near future.",
                 "IBM introduces quantum computing for commercial use with IBM Quantum Services.",
                 "Cybersecurity firm detects a new strain of malware targeting financial institutions.",
                 "Facebook faces criticism over data privacy concerns regarding its ad targeting algorithms.",
                 "Tesla's Full Self-Driving (FSD) Beta receives mixed reviews from early testers.",
                 "Microsoft Azure expands its cloud computing services with new data center locations.",
                 "Amazon launches its own line of custom-designed computer chips for AWS services.",
                 "Researchers develop a prototype for a wearable device that monitors blood glucose levels in real-time.",
                 "SpaceX announces plans for its first crewed mission to Mars within the next decade.",
                 "Google Cloud partners with leading healthcare organizations to develop AI solutions for medical imaging analysis.",
                 "The rise of quantum internet: Scientists achieve entanglement between distant nodes for secure communication.",
                 "Twitter introduces new features to combat misinformation and improve user safety.",
                 "Intel reveals plans for next-generation processors with improved performance and energy efficiency.",
                 "Autonomous drone delivery services begin testing in urban areas for faster package delivery.",
                 "Augmented reality glasses gain traction as major tech companies invest in AR development.",
                 "Volkswagen unveils its electric microbus concept with autonomous driving capabilities.",
                 "Sony announces the development of a new virtual reality headset for PlayStation 5.",
                 "Autonomous vehicles demonstrate advanced navigation capabilities in complex urban environments.",
                 "Qualcomm launches 5G modem for smartphones with improved speed and efficiency.",
                 "Artificial intelligence in healthcare: Startups develop AI-powered diagnostic tools for early disease detection.",
                 "Artificial intelligence is revolutionizing various industries.",
                 "Blockchain technology is changing the landscape of finance.",
                 "Machine learning algorithms are used for predictive analytics.",
                 "Quantum computing promises unprecedented computational power.",
                 "The Internet of Things connects devices for smart functionality.",
                 "Augmented reality enhances user experiences in gaming and beyond.",
                 "Cybersecurity threats are becoming more sophisticated.",
                 "Big data analytics help businesses make data-driven decisions.",
                 "Cloud computing allows for scalable and flexible IT infrastructure.",
                 "5G technology enables faster and more reliable wireless communication.",
                 "Virtual reality is being utilized for training and simulation purposes.",
                 "Robotics is advancing automation in manufacturing and beyond.",
                 "Self-driving cars use sensors and algorithms for navigation.",
                 "Natural language processing enables computers to understand human language.",
                 "Biometric authentication methods enhance security measures.",
                 "Renewable energy technologies are crucial for sustainable development.",
                 "Genetic engineering holds promise for medical advancements.",
                 "Nanotechnology enables manipulation of matter at the molecular level.",
                 "3D printing revolutionizes prototyping and manufacturing processes.",
                 "Wireless charging technology eliminates the need for cables.",
                 "Fintech startups are disrupting traditional banking services.",
                 "Smartphones have become ubiquitous in modern society.",
                 "Drones are used for aerial photography, surveillance, and delivery.",
                 "Robotic surgery enhances precision and reduces recovery times.",
                 "Artificial neural networks mimic the human brain for learning tasks.",
                 "Autonomous drones can be deployed for various applications.",
                 "Cryptocurrency transactions are secured through blockchain technology.",
                 "E-commerce platforms are experiencing rapid growth worldwide.",
                 "Renewable energy sources like solar and wind are gaining traction.",
                 "The adoption of 5G technology is driving innovation in telecommunications.",
                 "Edge computing brings processing closer to the data source for faster insights."],



        "health": ["A study reveals the benefits of meditation in reducing stress and anxiety.",
                   "Tips for a healthier lifestyle: prioritize sleep, exercise, and balanced nutrition.",
                   "The importance of regular health check-ups for early detection of diseases.",
                   "Yoga and mindfulness practices are linked to improved mental well-being.",
                   "How to boost your immune system naturally through diet and lifestyle changes."
                   "Benefits of regular exercise extend beyond physical health to include mental well-being.",
                   "Importance of staying hydrated for optimal cognitive function and overall health.",
                   "Mediterranean diet linked to lower risk of heart disease and improved longevity.",
                   "Mindful eating practices can help promote healthier eating habits and weight management.",
                   "Chronic stress negatively impacts the immune system and increases susceptibility to illness.",
                   "A recent study suggests that virtual reality therapy can be effective in treating phobias.",
                   "The benefits of meditation on mental health have been extensively studied and documented.",
                   "Researchers discover a new species of bacteria with potential applications in biotechnology.",
                   "The importance of maintaining a balanced diet for overall health and well-being.",
                   "Tips for managing stress and anxiety in the workplace.",
                   "Regular physical activity is essential for maintaining cardiovascular health.",
                   "The role of sleep in cognitive function and emotional regulation.",
                   "Strategies for improving mental resilience and coping with adversity.",
                   "The benefits of mindfulness meditation for reducing symptoms of depression and anxiety.",
                   "Tips for incorporating more fruits and vegetables into your daily diet for better nutrition.",
                   "The link between gut health and overall well-being: How to support a healthy gut microbiome.",
                   "Strategies for improving posture and reducing back pain in sedentary office environments.",
                   "The impact of screen time on sleep quality and strategies for minimizing its effects.",
                   "Herbal remedies for common ailments: exploring the use of natural supplements for health.",
                   "The benefits of regular stretching exercises for flexibility and injury prevention.",
                   "Mindfulness-based stress reduction techniques for managing chronic pain conditions.",
                   "The role of probiotics in gut health and immune system function.",
                   "Holistic approaches to mental health: Integrating diet, exercise, and mindfulness practices.",
                   "The importance of community support networks in maintaining mental health and resilience.",
                   "Understanding the mind-body connection: How emotional health impacts physical well-being.",
                   "Natural remedies for boosting energy levels and combating fatigue.",
                   "The impact of social media on mental health and strategies for digital detox.",
                   "Techniques for improving focus and concentration through mindfulness and meditation.",
                   "The benefits of outdoor activities for mental health and stress reduction.",
                   "Strategies for improving sleep hygiene and promoting restful sleep patterns.",
                   "The role of laughter in promoting physical and emotional health.",
                   "Mindful eating: How to cultivate awareness and enjoyment of food for better digestion.",
                   "The importance of self-care practices for maintaining overall health and well-being.",
                   "Regular exercise is important for maintaining overall health.",
                   "A balanced diet is essential for optimal nutrition and wellbeing.",
                   "Getting enough sleep is crucial for cognitive function and mood regulation.",
                   "Stress management techniques such as meditation can improve mental health.",
                   "Preventive healthcare measures can reduce the risk of chronic diseases.",
                   "Vaccinations protect against infectious diseases.",
                   "Regular medical check-ups can detect health issues early.",
                   "Proper hydration is important for bodily functions and energy levels.",
                   "Healthy lifestyle choices can lower the risk of heart disease.",
                   "Maintaining a healthy weight is beneficial for overall health.",
                   "Good hygiene practices help prevent the spread of illness.",
                   "Managing chronic conditions requires ongoing medical care.",
                   "Physical therapy can aid in rehabilitation after injuries.",
                   "Mental health services are important for addressing psychological disorders.",
                   "Nutritional supplements can complement a balanced diet.",
                   "Social connections contribute to mental and emotional wellbeing.",
                   "Cancer screenings are recommended for early detection.",
                   "Adequate sun protection reduces the risk of skin cancer.",
                   "Quitting smoking improves respiratory health and reduces cancer risk.",
                   "Regular dental check-ups are essential for oral health.",
                   "Healthy eating habits start with mindful food choices.",
                   "Regular exercise can boost immune function.",
                   "Managing stress levels is important for overall health.",
                   "Balanced hormones are necessary for proper bodily functions.",
                   "Adequate hydration supports kidney function and skin health.",
                   "Yoga promotes flexibility, strength, and stress relief.",
                   "Adequate rest is important for muscle recovery and growth.",
                   "Healthy fats are essential for brain health and hormone production.",
                   "Fiber-rich foods support digestive health.",
                   "Physical activity can improve cardiovascular health and reduce the risk of heart disease."]}
